defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: 'AKIAJIQLX3HN7ER5HS5A'
  aws_secret_access_key: 'VZkbILcotwyXE9L7y2+PJissxcFpLJcGOhJB1jkX'
  # To use AWS reduced redundancy storage.
  # aws_reduced_redundancy: true
  fog_directory: "follow-sample" # バケット名を指定
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  fog_region: 'ap-northeast-1'
  existing_remote_files: keep
  # To delete existing remote files.
  # existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  # gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

development:
  <<: *defaults
  # enabled: false

test:
  <<: *defaults
  # enabled: false

staging:
  <<: *defaults
  fog_directory: "follow-sample"

production:
  <<: *defaults
  fog_directory: "follow-sample"