default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: follow_sample_development
  username: root
  password: 

test:
  <<: *default
  database: follow_sample_test
  username: root
  password: 

production:
  <<: *default
  database: follow_sample_production
  username: root
  password: 
